const companyName = [
    "FORD",
    "CHEVROLET",
    "BMW",
    "MERCEDES-BENZ",
    "GMC",
    "AUDI",
    "TOYOTA",
    "PORSCHE",
    "VOLKSWAGEN",
    "DODGE",
    "MINI",
    "NISSAN",
    "KIA",
    "CADILLAC",
    "JEEP",
    "MAZDA",
    "HYUNDAI",
    "SUBARU",
    "JAGUAR",
    "LEXUS",
    "HONDA",
    "INFINITI",
    "CHRYSLER",
    "LAND ROVER",
    "MITSUBISHI",
    "BUICK",
    "RAM",
    "ACURA",
    "VOLVO",
    "LINCOLN",
    "FIAT",
    "SCION",
    "BENTLEY",
    "ROLLS-ROYCE",
    "ASTON MARTIN",
    "MASERATI",
    "LAMBORGHINI",
    "SMART",
    "SRT",
    "Other",
  ];

export default companyName
